FROM golang:1.23-alpine AS base
WORKDIR /app
COPY go.mod go.sum ./
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /http-server ./cmd/http

FROM scratch
WORKDIR /app
COPY --from=base /http-server .
CMD ["./http-server"]
