services:
  http-server:
    build:
      context: .
      dockerfile: Dockerfile.http
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - WORKER_INTERVAL=5s
    restart: unless-stopped
